name: Publish website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        name: Check out code
      
      - uses: actions/setup-node@v3
        name: Setup Node
        with:
          node-version: '18.5'
      
      - name: Build site
        run: |
          npm install --include=dev
          npx eleventy
          cp CNAME _site/CNAME

      - name: Build apps
        run: |
          cd app
          npm install
          npm run build
          cp dist/assets/*.js ../js/app.js

      - uses: peaceiris/actions-gh-pages@v3
        name: Deploy
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
